### ISSUE TITLE
Contract filters out too many samples

### ISSUE THREAD

**Issue by ProLoD** [mristin/aocdbc#12]
One of my solutions has a precondition limiting the input to lists with a minimum size.
In the current version of icontract-hypothesis, this means that too many samples are filtered out.
Do all tests need to pass before I can push my code to the repo or can I also include the tests that don't pass?

**Comment by mristin** [comment]
> Do all tests need to pass before I can push my code to the repo or can I also include the tests that don't pass?

I hand-picked which functions are to be tested (see [this line in day 8's test] and [that line]). Ideally, we can test everything automatically, but that is not possible. Either icontract-hypothesis does not infer the efficient strategy  (your case), or it is too laborious to specify all the necessary pre-conditions (see [this case in day 5]). I'd say we just do our best for the moment, and think later what we can fix or improve.

In your case, just pick what functions you can test, and merge it in. (But please make sure all the tests that you picked pass.)

[this line in day 8's test]: https://github.com/mristin/aocdbc/blob/5c9af0c7f5b6c83ec991789670fd873b19baf252/tests/test_day_8_handheld_halting.py#L35
[that line]: https://github.com/mristin/aocdbc/blob/5c9af0c7f5b6c83ec991789670fd873b19baf252/tests/test_day_8_handheld_halting.py#L40
[this case in day 5]: https://github.com/mristin/aocdbc/blob/5c9af0c7f5b6c83ec991789670fd873b19baf252/recorded_failures/day_5_binary_boarding/broken_step.py#L23

**Comment by ProLoD** [comment]
Alright, I only merged the functions that work and when an automatically inferred test fails, I commented it out and wrote the reason why (in my case not enough samples).
